[tox]
requires = tox-uv
env_list = py310, py311, py312, lint, typecheck

[testenv]
deps =
    pytest
    pytest-subtests
commands =
    pytest {posargs}

[testenv:lint]
skip_install = true
deps =
    black
    isort
    flake8
commands =
    black --check src/ tests/
    isort --check src/ tests/
    flake8 src/ tests/

[testenv:typecheck]
deps =
    mypy
    pytest
    pytest-subtests
commands =
    mypy
