from __future__ import annotations

from pathlib import Path
from typing import Protocol


class GitRepo(Protocol):
    @property
    def path(self) -> Path: ...
    def pull(self) -> None: ...
    def get_main_branch(self) -> str: ...
    def current_branch(self) -> str: ...
    def is_clean(self) -> bool: ...
    def get_skill_commit(self, skill_name: str) -> str: ...
    def verify_commit_content(self, commit: str, skill_name: str) -> bool: ...
