from __future__ import annotations

from pathlib import Path
from typing import Protocol


class GitRepo(Protocol):
    @property
    def path(self) -> Path: ...
    def pull(self) -> None: ...
    def get_main_branch(self) -> str: ...
    def current_branch(self) -> str: ...
    def is_clean(self) -> bool: ...
    def get_skill_commit(self, skill_name: str) -> str: ...
    def verify_commit_content(self, commit: str, skill_name: str) -> bool: ...
    def create_branch(self, name: str, from_commit: str) -> None: ...
    def checkout(self, branch: str) -> None: ...
    def commit_all(self, message: str) -> None: ...
    def rebase(self, onto: str) -> bool: ...
    def is_rebasing(self) -> bool: ...
    def rebase_continue(self) -> None: ...
    def rebase_abort(self) -> None: ...
    def fast_forward(self, branch: str) -> None: ...
    def delete_branch(self, name: str) -> None: ...
    def list_branches(self, pattern: str) -> list[str]: ...
